"""Proposal delivery and status tracking via Telegram."""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any

from eworks.agents.base import BaseAgent

logger = logging.getLogger(__name__)


class ProposalDelivery(BaseAgent):
    """Delivers proposals via Telegram and tracks status changes."""

    async def run(self, campaign_id: int) -> dict:
        """BaseAgent interface — not used directly."""
        return {"status": "ok"}

    def _get_reporter(self):
        """Get TelegramReporter instance."""
        from eworks.agents.prospector.reporter import TelegramReporter
        return TelegramReporter(
            bot_token=getattr(self.config, "telegram_bot_token", None),
            chat_id=getattr(self.config, "telegram_chat_id", None),
        )

    def _get_proposal(self, proposal_id: int) -> dict[str, Any]:
        conn = self.db.get_connection()
        row = conn.execute("SELECT * FROM proposals WHERE id=?", (proposal_id,)).fetchone()
        if not row:
            raise ValueError(f"Proposal {proposal_id} not found")
        return dict(row)

    def _get_client(self, client_id: int) -> dict[str, Any]:
        conn = self.db.get_connection()
        row = conn.execute("SELECT * FROM clients WHERE id=?", (client_id,)).fetchone()
        return dict(row) if row else {}

    async def deliver_via_telegram(self, proposal_id: int) -> bool:
        """Send proposal summary + file attachment via Telegram. Updates status to 'sent'."""
        proposal = self._get_proposal(proposal_id)
        client = self._get_client(proposal["client_id"])

        client_name = client.get("name", "Client")
        company = client.get("company", "")
        total_price = proposal.get("total_price", 0) or 0
        timeline_weeks = proposal.get("timeline_weeks", 0) or 0
        exec_summary = proposal.get("executive_summary", "") or ""
        pdf_path = proposal.get("pdf_path", "")
        title = proposal.get("title", f"Proposal #{proposal_id}")

        # Build summary message
        summary = (
            f"📄 <b>New Proposal Ready</b>\n\n"
            f"<b>Client:</b> {client_name}{' @ ' + company if company else ''}\n"
            f"<b>Title:</b> {title}\n"
            f"<b>Investment:</b> ${total_price:,.0f} USD\n"
            f"<b>Timeline:</b> {timeline_weeks} weeks\n"
            f"<b>Status:</b> Draft → Sending\n\n"
            f"<b>Executive Summary:</b>\n{exec_summary[:400]}{'...' if len(exec_summary) > 400 else ''}\n\n"
            f"<i>Proposal #{proposal_id} generated by Eworks OS Closer Agent</i>"
        )

        reporter = self._get_reporter()
        sent = await reporter.send(summary)

        # Try to send file attachment if available
        if sent and pdf_path and Path(pdf_path).exists():
            try:
                bot = reporter._get_bot()
                chat_id = reporter.chat_id
                with open(pdf_path, "rb") as f:
                    await bot.send_document(
                        chat_id=chat_id,
                        document=f,
                        filename=Path(pdf_path).name,
                        caption=f"📎 {title}",
                    )
                logger.info("Sent proposal file via Telegram: %s", pdf_path)
            except Exception as exc:
                logger.warning("Could not send file attachment: %s", exc)

        if sent:
            # Update status
            conn = self.db.get_connection()
            now = datetime.utcnow().isoformat()
            conn.execute(
                "UPDATE proposals SET status='sent', sent_at=? WHERE id=?",
                (now, proposal_id),
            )
            conn.commit()
            logger.info("Proposal %d marked as sent", proposal_id)

        return sent

    async def mark_accepted(self, proposal_id: int) -> bool:
        """Mark a proposal as accepted."""
        conn = self.db.get_connection()
        now = datetime.utcnow().isoformat()
        conn.execute(
            "UPDATE proposals SET status='accepted', accepted_at=? WHERE id=?",
            (now, proposal_id),
        )
        conn.commit()

        # Also update client status to 'won'
        proposal = self._get_proposal(proposal_id)
        conn.execute(
            "UPDATE clients SET status='won' WHERE id=?",
            (proposal["client_id"],),
        )
        conn.commit()
        logger.info("Proposal %d accepted!", proposal_id)
        return True

    async def mark_rejected(self, proposal_id: int, reason: str | None = None) -> bool:
        """Mark a proposal as rejected with optional reason."""
        conn = self.db.get_connection()
        conn.execute(
            "UPDATE proposals SET status='rejected' WHERE id=?",
            (proposal_id,),
        )
        conn.commit()

        # Update client notes with rejection reason
        if reason:
            proposal = self._get_proposal(proposal_id)
            existing_notes = self._get_client(proposal["client_id"]).get("notes", "") or ""
            new_note = f"\n[{datetime.utcnow().date()}] Proposal #{proposal_id} rejected: {reason}"
            conn.execute(
                "UPDATE clients SET status='lost', notes=? WHERE id=?",
                (existing_notes + new_note, proposal["client_id"]),
            )
            conn.commit()
        logger.info("Proposal %d rejected (reason: %s)", proposal_id, reason or "not specified")
        return True

    async def get_pipeline_summary(self) -> dict[str, Any]:
        """Return pipeline stats: counts by status and total value in pipeline."""
        conn = self.db.get_connection()

        rows = conn.execute(
            """
            SELECT
                status,
                COUNT(*) as count,
                COALESCE(SUM(total_price), 0) as value
            FROM proposals
            GROUP BY status
            """
        ).fetchall()

        summary: dict[str, Any] = {
            "draft": 0,
            "sent": 0,
            "viewed": 0,
            "accepted": 0,
            "rejected": 0,
            "expired": 0,
            "total_value_pipeline": 0.0,
            "total_value_won": 0.0,
        }

        for row in rows:
            status = row["status"]
            count = row["count"]
            value = row["value"]
            if status in summary:
                summary[status] = count
            # Pipeline = sent + viewed + accepted
            if status in ("sent", "viewed", "accepted"):
                summary["total_value_pipeline"] += value
            if status == "accepted":
                summary["total_value_won"] = value

        return summary
